branches:
  only:
    - master
install:
  - bundle install
  - npm install phantomjs -g
  - npm install casperjs -g
before_install:
  - set -e
  - openssl aes-256-cbc -K $encrypted_091a05d4487d_key -iv $encrypted_091a05d4487d_iv -in id_rsa.enc -out id_rsa -d
  - sudo chown -R $(whoami) ~/.ssh
  - mkdir -p ~/.ssh
  - mv id_rsa ~/.ssh
  - ls -al ~/.ssh
  - chmod -R 600 ~/.ssh
  - ls -al ~/.ssh
script:
  - set -e
  - _test/run.sh
  - git config --global user.email "travis@teamed.io"
  - git config --global user.name "Travis"
  - jgd
