branches:
  only:
    - master
env:
  global:
    - secure: "fYhWYdDrGNiaSxTGmZ72TEV1PZgpSmjD953jXUxUFcmd0SYEWDtTMAToGmngfgyYE+LIaYnOq/Y6Mq01CGS7hDCifE29ShB8UY1gLUxG7piSjiYuaEDoUnKV+xFHgrKveIDEFG10Hv/gKyL/M4hz9dkHNRZQA0XPAwR+l7yhfpA="
install:
  - bundle install
  - npm install phantomjs -g
  - npm install casperjs -g
script:
  - set -x
  - set -e
  - _test/run.sh
  - git config --global user.email "travis@teamed.io"
  - git config --global user.name "Travis"
  - jgd -u https://yegor256:$PASSWORD@github.com/tpc2/teamed.io.git

