name: teamed.io
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: :year/:month/:day/:title.html

# see https://github.com/noct/jekyll-sass
gems: ['jekyll-sass']
sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: false

# see https://github.com/kinnetica/jekyll-plugins
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/rss.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequence"
  priority_name: "priority"
