name: teamed.io
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
permalink: :year/:month/:day/:title.html

# see https://github.com/noct/jekyll-sass
gems: ['jekyll-sass']
sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: false
